/* This file was generated by the "svnrev" utility.
 * You should not modify it manually, as it may be re-generated.
 *
 */

#ifndef SVNREV_H
#define SVNREV_H

#define SVN_REV		597861
#define SVN_REVSTR	"597861"
#define SVN_REVDATE	"2013-08-16"
#define SVN_REVSTAMP	20130816L

#endif /* SVNREV_H */
