set(CMAKE_FIND_ROOT_PATH 
/opt/fftw/default/x86_64     #fftw3 path for bluewater
/usr/local/apps/fftw/intel101_hydra/2.1.5
/usr/local/apps/mvapich2/220b-intel140
/sw/xe/magma/1.5.0/magma-1.5.0
/sw/xe/magma/1.6.1/cnl5.2_gnu4.8.2
/usr/lib64/mpi/gcc/openmpi/
/sw/xc30/boost/1.55.0/cle5.1_gnu4.8.2
/opt/local/lib/libxc         #libxc from Macports
/sw/xk6/boost/1.57.0/cle5.2_gnu4.8.2
/home/luw/Downloads/magma-1.6.2/build
/sw/xk6/magma/1.6.2/sles11.3_gnu4.8.2/
/opt/cray/fftw/3.3.4.8/x86_64/
)
