#!/bin/bash
#
# Change to your account
# Also change in the srun command below
##SBATCH -A MAT151
#SBATCH -A MAT739
#
# Job naming stuff
#SBATCH -J rmg_input
#SBATCH -o %x-%j.out
#SBATCH -e %x-%j.err
#
# Requested time
#SBATCH -t 00:30:00
#
# Requested queue
##SBATCH -p batch
#SBATCH -q debug
#
# Number of frontier nodes to use.
#SBATCH -N 30
#
# OMP num threads. Frontier reserves 8 of 64 cores on a node
# for the system. There are 8 logical GPUs per node so we use
# 8 MPI tasks/node with 7 OMP threads per node
export OMP_NUM_THREADS=7
#
# RMG threads. Max of 7 same as for OMP_NUM_THREADS but in some
# cases running with fewer may yield better performance because
# of cache effects.
export RMG_NUM_THREADS=5
#
# Don't change these
export MPICH_OFI_NIC_POLICY=NUMA
#
# Load modules
module reset
module load PrgEnv-gnu  
module load cpe/26.03
module load cray-mpich/9.1.0
module load rocm/7.0.2
module swap rocm/7.0.2 rocm/7.2.0
module load craype-accel-amd-gfx90a
module load craype-x86-trento
module load boost/1.88.0
module load cray-fftw
module load cray-hdf5-parallel
export LD_LIBRARY_PATH=$CRAY_LD_LIBRARY_PATH:$LD_LIBRARY_PATH
export MPICH_GPU_SUPPORT_ENABLED=0

# Set variables. Update binary to your own if you have built it yourself
RMG_BINARY=/lustre/orion/mat739/proj-shared/elbriggs/usr/bin/rmg-gpu-rocm7.2
NNODES=30
GPUS_PER_NODE=8

srun -A MAT739 --ntasks=$(($GPUS_PER_NODE * $NNODES)) -u -c7 --cpu-bind=sockets --threads-per-core=1 --gpus-per-node=$GPUS_PER_NODE  --ntasks-per-gpu=1 --gpu-bind=closest $RMG_BINARY input

