#!/bin/bash 
 
#SBATCH -p batch
#SBATCH --nodes 2
#SBATCH --gpus-per-node 8
#SBATCH --ntasks 16
#SBATCH --cpus-per-task 7
#SBATCH --gpus-per-task=1
#SBATCH --gpu-bind=closest
#SBATCH -t 0:30:00
#SBATCH -o stdout
#SBATCH -A MAT739
 
# OMP num threads. Frontier reserves 8 of 64 cores on a node
# for the system. There are 8 logical GPUs per node so we use
# 8 MPI tasks/node with 7 OMP threads per node
export OMP_NUM_THREADS=7

# RMG threads. Max of 7 same as for OMP_NUM_THREADS but in some
# cases running with fewer may yield better performance because
# of cache effects.
export RMG_NUM_THREADS=6
export MPICH_OFI_NIC_POLICY=NUMA

module load PrgEnv-gnu/8.6.0
module load gcc-native/13.2
module load cmake
module load cray-mpich/9.0.1
module load Core/24.00
module load bzip2
module load boost/1.85.0
module load craype-x86-milan
module load cray-fftw
module load cray-hdf5-parallel
module load rocm/7.0.2
export MPICH_GPU_SUPPORT_ENABLED=0
export http_proxy=http://proxy.ccs.ornl.gov:3128
export https_proxy=http://proxy.ccs.ornl.gov:3128

./frontier.sh
cd $SLURM_SUBMIT_DIR/build-frontier-gpu
ctest -D ExperimentalTest
ctest -D ExperimentalSubmit
