add_library (ON_Common
    MatrixKpoint.cpp
 Exx_on.cpp
 Scf_on_proj.cpp
 WriteWaveFunctions.cpp
 WriteCij.cpp
 read_orbitals_on.cpp
 CalculateResidual.cpp
 get_te.cpp
 ReadDataFromRMG.cpp
 UpdatePot.cpp
 DiagScalapack.cpp
 DiagGpu.cpp
 write_restart.cpp
 init_wf_lcao.cpp
 allocate_matrix.cpp
 CMakeLists.txt
 Fill_on.cpp
 get_sum_eig.cpp
 InitON.cpp
 init_pe_on.cpp
 quench.cpp
 rand0.cpp
 read_data.cpp
 write_data.cpp
 write_eigs.cpp
 ZeroBoundary.cpp
 CheckConvergence.cpp
)
include_directories("${RMG_SOURCE_DIR}/ON/Headers/")
include_directories("${RMG_BINARY_DIR}/ON/Headers/")
