FUNCTION( COPY_DIRECTORY SRC_DIR DST_DIR)
   EXECUTE_PROCESS( COMMAND ${CMAKE_COMMAND} -E copy_directory "${SRC_DIR}" "${DST_DIR}" )
   # message(${SRC_DIR})
   # message(${DST_DIR})

ENDFUNCTION()

FUNCTION(RMG_RUN_CHECK_CPU TESTNAME PROCS)
    message("${CMAKE_CURRENT_BINARY_DIR}" )

    SET(RMG_CPU "${CMAKE_BINARY_DIR}/rmg-cpu") 
    SET(CHECK_ENE "${CMAKE_SOURCE_DIR}/tests/check_totalt_energy.py")
    message(${RMG_CPU})
    
    SET(WORKDIR "${CMAKE_CURRENT_BINARY_DIR}/${TESTNAME}/RMG" )
    SET(MPIEXEC "mpirun")
    SET(MPIEXEC_NUMPROC_FLAG " -n")
    
    ADD_TEST(NAME ${TESTNAME}
            COMMAND ${CMAKE_COMMAND}
    -DWORKDIR=${WORKDIR}
    -DRMG_CPU=${RMG_CPU}
    -DPROCS=${PROCS}
    -P ${CMAKE_SOURCE_DIR}/cmake/runtest.cmake)

    ADD_TEST(NAME ${TESTNAME}_check_total_energy COMMAND ${CHECK_ENE} WORKING_DIRECTORY ${WORKDIR})
    
#    ADD_TEST(NAME ${TESTNAME} COMMAND rm -r ${WORKDIR}/input.00.log ${WORKDIR}/input.00.options ${WORKDIR}/input.00.rmsdv.xmgr ${WORKDIR}/Waves)
#    SET_TESTS_PROPERTIES( ${TESTNAME}-rm PROPERTIES ENVIRONMENT OMP_NUM_THREADS=1 PROCESSORS ${PROCS} PROCESSOR_AFFINITY TRUE WORKING_DIRECTORY ${WORKDIR} )
  #  ADD_TEST(NAME ${TESTNAME} COMMAND ${MPIEXEC} ${MPIEXEC_NUMPROC_FLAG} ${PROCS} ${RMG_CPU} input )
  #  SET_TESTS_PROPERTIES( ${TESTNAME} PROPERTIES ENVIRONMENT OMP_NUM_THREADS=1 PROCESSORS ${PROCS} PROCESSOR_AFFINITY TRUE WORKING_DIRECTORY ${WORKDIR} )

ENDFUNCTION()
