FUNCTION( COPY_DIRECTORY SRC_DIR DST_DIR)
   EXECUTE_PROCESS( COMMAND ${CMAKE_COMMAND} -E copy_directory "${SRC_DIR}" "${DST_DIR}" )
   # message(${SRC_DIR})
   # message(${DST_DIR})

ENDFUNCTION()

FUNCTION(RMG_RUN_CHECK TESTNAME TEST_DIR RMG_EXE PROCS)
   # message("${CMAKE_CURRENT_BINARY_DIR}" )

    SET(CHECK_ENE "${CMAKE_SOURCE_DIR}/tests/check_totalt_energy.py")
   # message(${RMG_CPU})
    
    SET(WORKDIR "${CMAKE_CURRENT_BINARY_DIR}/${TEST_DIR}" )
    SET(MPIEXEC "mpirun")
    SET(MPIEXEC_NUMPROC_FLAG " -n")
    
    ADD_TEST(NAME ${TESTNAME}
            COMMAND ${CMAKE_COMMAND}
    -DWORKDIR=${WORKDIR}
    -DRMG_EXE=${RMG_EXE}
    -DPROCS=${PROCS}
    -P ${CMAKE_SOURCE_DIR}/cmake/runtest.cmake)

    ADD_TEST(NAME ${TESTNAME}_check_total_energy COMMAND ${CHECK_ENE} WORKING_DIRECTORY ${WORKDIR})
    SET_TESTS_PROPERTIES( ${TESTNAME}_check_total_energy PROPERTIES PASS_REGULAR_EXPRESSION "pass")
    
ENDFUNCTION()
