file(REMOVE_RECURSE "${WORKDIR}")
EXECUTE_PROCESS( COMMAND ${CMAKE_COMMAND} -E copy_directory "${SRC_DIR}" "${WORKDIR}" )

execute_process(COMMAND ${MPIEXEC} -n ${PROCS} ${RMG_ON} input WORKING_DIRECTORY ${WORKDIR}/lead1)
execute_process(COMMAND ${MPIEXEC} -n ${PROCS} ${RMG_ON} input WORKING_DIRECTORY ${WORKDIR}/center)
execute_process(COMMAND ${MPIEXEC} -n ${PROCS} ${RMG_NEGF} input WORKING_DIRECTORY ${WORKDIR}/3lead_lead1)
execute_process(COMMAND ${MPIEXEC} -n ${PROCS} ${RMG_NEGF} input.110 WORKING_DIRECTORY ${WORKDIR}/3lead_lead1)
execute_process(COMMAND ${MPIEXEC} -n ${PROCS} ${RMG_NEGF} input WORKING_DIRECTORY ${WORKDIR}/bias_0.0)
execute_process(COMMAND ${MPIEXEC} -n ${PROCS} ${RMG_NEGF} input.110 WORKING_DIRECTORY ${WORKDIR}/bias_0.0)
execute_process(COMMAND python3 ${CHECK_COND}  WORKING_DIRECTORY ${WORKDIR}/bias_0.0)
file(REMOVE_RECURSE "${WORKDIR}/lead1/Waves")
file(REMOVE_RECURSE "${WORKDIR}/center/Waves")
file(REMOVE_RECURSE "${WORKDIR}/3lead_lead1/Waves")
file(REMOVE_RECURSE "${WORKDIR}/bias_0.0/Waves")
