/* This file was generated by the "svnrev" utility.
 * You should not modify it manually, as it may be re-generated.
 *
 */

#ifndef SVNREV_H
#define SVNREV_H

#define SVN_REV		1265
#define SVN_REVSTR	"1265"
#define SVN_REVDATE	"2011-02-22"
#define SVN_REVSTAMP	20110222L

#endif /* SVNREV_H */
